# Generated by Django 5.0.6 on 2024-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0004_alter_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
