# Generated by Django 5.0.6 on 2024-07-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0006_alter_movie_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
