# Generated by Django 5.0.6 on 2024-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fapp', '0007_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='img')),
                ('Year', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
